#!/bin/bash 
mode: 'inference'
use_cuda: 1 # 1 for True, 0 for False
num_gpu: 1
sampling_rate: 16000
network: "MossFormer2_SS_16K"  ##network type
checkpoint_dir: "checkpoints/MossFormer2_SS_16K"

input_path: "data/English_mix.scp"  # an input dir or input scp file
output_dir: "/mnt/usb-Realtek_RTL9210B-CG_012345679039-0:0-part1/Datasets/English_mix_data" ## output dir to store processed audio

# decode parameters
one_time_decode_length: 60 #maximum segment length for one-pass decoding (seconds), longer audio (>60s) will use segmented decoding
decode_window: 1 #one-pass decoding length

num_spks: 2
encoder_kernel_size: 16
encoder_embedding_dim: 512
mossformer_sequence_dim: 512
num_mossformer_layer: 24
